--- # This is an Ansible script to deploy Gobackup on a desired number of machines.

- hosts: all
  user: root
  gather_facts: true
  vars_files: ./vars.yaml
  tasks:

    - name: Update the packages (APT based)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update the packages (YUM based)
      yum:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "RedHat"

    - name: Create a base directory for Gobackup
      file:
        path: "{{ base_directory }}"
        state: directory
        mode: '0775'

    - name: Create other sub-directories
      file:
        path: "{{ base_directory }}/{{ item }}"
        state: directory
        mode: '0775'
      with_items:
        - config
        - data

    - name: Copy the docker-compose file
      copy:
        src: ./docker-compose/docker-compose.yaml
        dest: "{{ base_directory }}/docker-compose.yaml"

    - name: Add docker-compose version to the .env file
      lineinfile:
        path: "{{ base_directory }}/.env"
        line: "GOBACKUP_VERSION={{ gobackup_version }}"
        create: true

    - name: Copy Gobackup config files
      copy:
        src: ./configs/{{ config_file }}
        dest: "{{ base_directory }}/config/gobackup.yml"

    - name: Start gobackup service
      shell: cd "{{ base_directory }}" && docker compose up -d
